apiVersion: v1
kind: PersistentVolume
metadata:
  name: asdsd
spec:
  volumeMode: Filesystem
  accessMode:
    - ReadOnlyMany
    - ReadWriteOnce
    - ReadWriteMany
  capacity:
    storage: 10Mi
  persistentVolumeReclaimPolicy: Retain/Delete/Recycle
  storageClassName: manual
  hostPath:
    - type: Directory
      path: /lib
  claimRef:
    name: foo-pvc
    namespace: foo
