apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaSet
spec:
  replicas: 3
  selector:
    matchLabels:
      label: podLabel
  template:
    metadata:
      labels:
        label: podLabel
    spec:
      containers:
        - name: containerName
          image: nginx
