apiVersion: apps/v1
kind: ResourceQuota
metadata:
  name: qoutaname
  namespace: dev

spec:
  hard:
    pods: 10
    requests.memory: 1
    requests.cpu: 1
    limit.memory: 1
    limit.cpu: 1
    persistentvolumeclaims: "5"
    requests.storage: "5Gi"
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values: ["low"]
