apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testrole
rules:
  - apiGroup: [""]
    resources: ["pod", "deployment"]
    resourceNames: ["testPod"]
    verbs: ["create", "get", "list"]
